# Generated by Django 4.2.2 on 2024-03-17 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='black_player',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='time_control',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='white_player',
        ),
        migrations.AddField(
            model_name='chessgame',
            name='blackPlayer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='blackPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='timeControl',
            field=models.CharField(default='30', max_length=15),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='whitePlayer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whitePlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
