# Generated by Django 4.2.2 on 2024-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_chessgame_black_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'active'), ('F', 'finished')], default='pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='chessmove',
            name='promotion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
