# Generated by Django 4.2.2 on 2024-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_chessgame_status_alter_chessmove_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board_state',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'active'), ('F', 'finished')], default='pending', max_length=10),
        ),
    ]
