# Generated by Django 4.2.2 on 2024-03-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_player_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='blackPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='whitePlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitePlayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
