# Generated by Django 4.2.2 on 2024-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_chessgame_blackplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('finished', 'finished')], default='pending', max_length=10),
        ),
    ]
